### PR TITLE
Revisions: See Matthew Cachia's comments RE: Chapter 03

### PR DESCRIPTION
**Pull request by mcac0006**
Revisions: See Matthew Cachia's comments RE: Chapter 03.

Changes made:

- gradle and maven projects merged together as both build tools can operate on the same project: less code to maintain
- maven's project failed: missing flyway application.yml
- downgraded to JDK 8: this would reach a much broader audience and jOOQ works pefectly fine
- REST controller removed from spring boot (and also removed `spring-boot-starter-web`) as it is beyond the scope of the project. Relocated the running code into a test suite - this would avoid binding a port.

### CODE REVIEW

**Comment by lukaseder** [comment]
Hi @mcac0006, I take that you're reviewing @AnghelLeonard's book? Nice to meet you! :)

> * downgraded to JDK 8: this would reach a much broader audience and jOOQ works pefectly fine

I've been postponing dropping Java 8 support from the jOOQ Open Source Edition until a more "opportune" moment, supporting it only in the jOOQ Professional and Enterprise Editions: https://github.com/jOOQ/jOOQ/issues/7789.

Currently, regrettably, the Java 8 market share is still too high for such a move. But chances are high I'll be doing this for jOOQ 3.16 along with the Java 17 LTS release. The new strategy will be that the jOOQ Open Source Edition only supports the last two LTS of Java, and older ones are supported only in the commercial distributions.

With that in mind, my recommendation for this book is to base all examples on at least Java 11.

**Comment by mcac0006** [comment]
Hi @lukaseder ,

Yes, I am. Hi! 👋 

That's perfectly fine - I'll push another update to require JDK 11+ in a few hours.

**Comment by AnghelLeonard** [comment]
Hi @mcac0006 :) It was nice if Packt was informed me about the fact that you are doing this review. I had no idea about it. However, I consider the code as WIP (I have a list of modifications and so on) so please postpone this review for now.

Thanks!

**Comment by mcac0006** [comment]
Hi @AnghelLeonard,

Apologies if this felt intrusive - I would have thought you have been informed.

No problem, I will avoid any PRs.

**Comment by AnghelLeonard** [comment]
No problem. Thanks for understanding :)

**Pull request closed without merging**
